GET http://localhost:5017/abouts

###


PUT http://localhost:5017/abouts/5fb65a14e4d7eb32b04cc4e9
Content-Type: application/json

{
    "tekst": "Intel Celeron tesaasd fasfad "
}

###

POST http://localhost:5017/admin/about
Content-Type: application/json

{
    "tekst": "Her er vores about tekst right side"
}